#!/usr/bin/env python3
"""Plot the full-quantum effective IPL exponent n_eff(T) for 4He and 3He from this
project's phase-shift engine, overlaid with the Cencek et al. 2012 tabulated values
(reproducing Bell, J. Chem. Phys. 152, 164508 (2020), Fig. 8).

- Engine data: figures/neff_engine.csv  (generated by `cargo run --release --example neff_curve`).
- Cencek overlay: docs/refs/he/s4_he4prop.txt (4He), s5_he3prop.txt (3He). These SI files
  are AIP-copyrighted and gitignored (local-only); their n_eff is derived on the fly as
  n_eff = -3(B + TB') / (2 TB' + T^2 B''). If absent, the engine curve is plotted alone.

Usage:  python3 scripts/plot_neff.py
Output: figures/neff_he_quantum.png
"""
import csv
import os

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ENGINE_CSV = os.path.join(ROOT, "figures", "neff_engine.csv")
CENCEK = {
    "4He": os.path.join(ROOT, "docs", "refs", "he", "s4_he4prop.txt"),
    "3He": os.path.join(ROOT, "docs", "refs", "he", "s5_he3prop.txt"),
}
OUT = os.path.join(ROOT, "figures", "neff_he_quantum.png")


def read_engine():
    """Return {'4He': (Ts, neffs), '3He': (Ts, neffs)} from the engine CSV."""
    t, n4, n3 = [], [], []
    with open(ENGINE_CSV) as f:
        for row in csv.DictReader(f):
            t.append(float(row["T"]))
            n4.append(float(row["neff_he4"]))
            n3.append(float(row["neff_he3"]))
    return {"4He": (t, n4), "3He": (t, n3)}


def read_cencek(path):
    """Parse a Cencek SI property table -> (Ts, neffs) via n_eff from cols B, TB', T^2B''."""
    ts, ns = [], []
    if not os.path.exists(path):
        return None
    with open(path) as f:
        for line in f:
            parts = line.split("\t")
            try:
                t = float(parts[0])
                b, tbp, t2bpp = float(parts[1]), float(parts[2]), float(parts[3])
            except (ValueError, IndexError):
                continue  # header / unit rows
            denom = 2.0 * tbp + t2bpp
            if denom == 0.0:
                continue
            ts.append(t)
            ns.append(-3.0 * (b + tbp) / denom)
    return ts, ns


# 3He's n_eff (Eq. 11) has a genuine pole near ~18 K where 2TB'+T^2B'' crosses zero
# (Cencek's own table shows it too). Mask the off-scale points so the pole doesn't draw a
# vertical streak / dominate the axis; the surrounding branches still validate vs Cencek.
YCLIP = 220.0


def masked(ts, ns):
    """NaN-out points with |n_eff| > YCLIP (breaks the line across the pole)."""
    return ts, [n if abs(n) <= YCLIP else float("nan") for n in ns]


def main():
    engine = read_engine()
    fig, ax = plt.subplots(figsize=(7.2, 5.0))
    colors = {"4He": "#1f77b4", "3He": "#d62728"}
    tmax = max(max(engine[k][0]) for k in engine)
    for iso in ("4He", "3He"):
        et, en = masked(*engine[iso])
        ax.plot(et, en, "-", color=colors[iso], lw=2, label=f"{iso} (this work, phase shifts)")
        cen = read_cencek(CENCEK[iso])
        if cen:
            ct = [t for t in cen[0] if t <= tmax * 1.05]
            cn = [n for t, n in zip(*cen) if t <= tmax * 1.05]
            ct, cn = masked(ct, cn)
            ax.plot(ct, cn, "o", color=colors[iso], ms=5, mfc="none", mew=1.3,
                    label=f"{iso} (Cencek 2012)")
    ax.axhline(0.0, color="0.6", lw=0.7)
    ax.set_xscale("log")
    ax.set_ylim(-70, 160)
    ax.set_xlabel("T  /  K")
    ax.set_ylabel(r"$n_{\mathrm{eff}}$")
    ax.set_title("Full-quantum effective IPL exponent of helium\n(reproducing Bell 2020, Fig. 8)")
    ax.grid(True, which="both", alpha=0.25)
    ax.legend(frameon=False, fontsize=9, loc="upper right")
    ax.annotate(
        "$^3$He: $n_{\\mathrm{eff}}$ pole near ~18 K\n(2TB$'$+T$^2$B$''$ → 0; in Cencek too)",
        xy=(18, -55), fontsize=8, color=colors["3He"], ha="center",
    )
    fig.tight_layout()
    fig.savefig(OUT, dpi=150)
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
