//! potter_poc — proof of concept that a DSL-defined pair potential can be
//! integrated to virial coefficients (B2, B3) entirely in (pure) Rust, and
//! shipped as a self-contained WASM module that a host (node.js) calls into.

pub mod aot;
pub mod dsl;
pub mod fastpot;
pub mod integrate;
pub mod physics;

// cranelift emits native machine code, so the JIT backend is native-only.
#[cfg(not(target_arch = "wasm32"))]
pub mod jit;
#[cfg(not(target_arch = "wasm32"))]
pub use jit::JitPotential;

pub use fastpot::FastPotential;
pub use physics::{
    b2, b2_finegrid, b2_lj_series, b2_v, b2_v_grid, b3, b3_v, b3_v_grid, CsePotential, Potential,
    LJ_BOYLE_TSTAR,
};

/// Compile a DSL potential string and compute B2 at temperature `t`.
pub fn b2_from_dsl(src: &str, eps: f64, sig: f64, t: f64, tol: f64) -> Result<f64, String> {
    let pot = Potential::compile(src, eps, sig)?;
    Ok(b2(&pot, t, tol))
}

/// Compile a DSL potential string and compute B3 at temperature `t`.
pub fn b3_from_dsl(src: &str, eps: f64, sig: f64, t: f64, tol: f64) -> Result<f64, String> {
    let pot = Potential::compile(src, eps, sig)?;
    Ok(b3(&pot, t, tol))
}

/// Raw C-ABI exports for the WASM "plugin". The host writes the DSL string into
/// linear memory via `poc_alloc`, then calls `poc_b2` / `poc_b3`.
#[cfg(target_arch = "wasm32")]
mod wasm_exports {
    use super::{b2_from_dsl, b3_from_dsl};
    use std::alloc::{alloc, dealloc, Layout};

    #[no_mangle]
    pub extern "C" fn poc_alloc(len: usize) -> *mut u8 {
        if len == 0 {
            return std::ptr::null_mut();
        }
        let layout = Layout::from_size_align(len, 1).unwrap();
        unsafe { alloc(layout) }
    }

    #[no_mangle]
    pub extern "C" fn poc_dealloc(ptr: *mut u8, len: usize) {
        if ptr.is_null() || len == 0 {
            return;
        }
        let layout = Layout::from_size_align(len, 1).unwrap();
        unsafe { dealloc(ptr, layout) }
    }

    fn read_dsl<'a>(ptr: *const u8, len: usize) -> Option<&'a str> {
        let slice = unsafe { std::slice::from_raw_parts(ptr, len) };
        std::str::from_utf8(slice).ok()
    }

    /// Parse the DSL string at [ptr, ptr+len) and return B2(eps, sig, t). NaN on error.
    #[no_mangle]
    pub extern "C" fn poc_b2(ptr: *const u8, len: usize, eps: f64, sig: f64, t: f64) -> f64 {
        match read_dsl(ptr, len) {
            Some(src) => b2_from_dsl(src, eps, sig, t, 1e-12).unwrap_or(f64::NAN),
            None => f64::NAN,
        }
    }

    /// Parse the DSL string at [ptr, ptr+len) and return B3(eps, sig, t). NaN on error.
    #[no_mangle]
    pub extern "C" fn poc_b3(ptr: *const u8, len: usize, eps: f64, sig: f64, t: f64) -> f64 {
        match read_dsl(ptr, len) {
            Some(src) => b3_from_dsl(src, eps, sig, t, 1e-7).unwrap_or(f64::NAN),
            None => f64::NAN,
        }
    }

    /// AOT-compile the DSL at [ptr,len) to a standalone wasm module exporting
    /// `potential(r,eps,sig)`. Returns the generated bytes packed as
    /// `(ptr << 32) | len` (0 on parse error). Free with `poc_free`.
    #[no_mangle]
    pub extern "C" fn poc_compile_wasm(ptr: *const u8, len: usize) -> u64 {
        let src = match read_dsl(ptr, len) {
            Some(s) => s,
            None => return 0,
        };
        match crate::aot::compile_to_wasm(src, &["r", "eps", "sig"]) {
            Ok(bytes) => {
                let n = bytes.len() as u64;
                let boxed = bytes.into_boxed_slice();
                let p = boxed.as_ptr() as u64;
                std::mem::forget(boxed); // ownership handed to caller; freed via poc_free
                (p << 32) | n
            }
            Err(_) => 0,
        }
    }

    /// Free a buffer returned by `poc_compile_wasm`.
    #[no_mangle]
    pub extern "C" fn poc_free(ptr: *mut u8, len: usize) {
        if !ptr.is_null() && len > 0 {
            unsafe {
                drop(Vec::from_raw_parts(ptr, len, len));
            }
        }
    }

    /// Exact LJ (12-6) reduced B2 via the HCB Gamma series (for the exact-solution
    /// overlay). `tstar` = T/eps; multiply the result by sig^3 for general sigma.
    #[no_mangle]
    pub extern "C" fn poc_b2_lj_series(tstar: f64, nterms: u32) -> f64 {
        crate::physics::b2_lj_series(tstar, nterms as usize)
    }

    /// Gamma function (for the inverse-power exact solution: B2 = (2pi/3) sig^3
    /// Gamma(1-3/n) (T/eps)^(-3/n)).
    #[no_mangle]
    pub extern "C" fn poc_tgamma(x: f64) -> f64 {
        libm::tgamma(x)
    }
}
